kind: Service
apiVersion: v1
metadata:
  name: jenkins
  creationTimestamp: null
  labels:
    name: jenkins
    role: frontend
spec:
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: jenkins-http
      nodePort: 0
    - name: discovery
      protocol: TCP
      port: 50000
      targetPort: jenkins-discovery
      nodePort: 0
  selector:
    name: jenkins
    role: leader
  clusterIP: ''
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
